### ISSUE TITLE
How to run your library and whether it predicts personality with text or not?

### ISSUE THREAD

**Issue by JafferWilson** [TeoTwawki/mars-sim-bork#1]

**Comment by mokun** [comment]
Hi @JafferWilson, 

> How to run your library
Please take a look at our github repo (here)[https://github.com/mars-sim/mars-sim]. You can download the 3.1.0 preview 8 binary from Sourceforge.

> whether it predicts personality with text or not?
We incorporated both the Big Five Personality Model and the Myers-Briggs Type Indicator and randomly give a score on each trait for each settlers. These traits would impacts their task preferences and job choice.

If you want to dig into the codes, see PersonalityType.java (where Myers-Briggs is implemented), PersonalityTraitManager.java and PersonalityTraitType.java (where the Big Five is implemented). 

You are definitely welcome to provide your feedback and contribute to our project.

**Comment by TeoTwawki** [comment]
huh, didn't even realize my fork had the issues thing enabled..

**Comment by TeoTwawki** [comment]
also its somehow showing as mirror instead of fork now. something went wrong..

**Comment by TeoTwawki** [comment]
oh, did you recently move off sf to gh? I might have cloned from sf then forgot and thats why

**Comment by mokun** [comment]
@TeoTwawki, yes we just moved from SF to GH early this year, while you cloned the repo to GH over a year ago, right ?

You're welcome to contribute to mars-sim by all means.

**Comment by TeoTwawki** [comment]
👍 I remade my fork so I can more easily contribute when I have free time. See you around going to nuke this old copy now
